name: Build and Deploy

on:
  push:
    branches: [ '**' ]
    tags: [ '*' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-22.04 
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.20.2'
        cache: 'npm'
        
    - name: Install Angular CLI
      run: npm install -g @angular/cli@10.0.5
      
    - name: Install dependencies
      run: npm install
      
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      
    - name: Run tests
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      
    - name: Build
      run: ng build --prod
      
    # Deploy only on tags pushed to master
#    - name: Trigger deployment
#      if: startsWith(github.ref, 'refs/tags/') && github.ref == 'refs/heads/master'
#      run: |

